services:
  next:
    build: .
    ports:
      - "3000:3000"
    develop:
      watch:
        - path: .
          action: sync
          target: /app
        - path: ./package.json
          target: /app/package.json
          action: sync+restart
        - path: ./yarn.lock
          target: /app/yarn.lock
          action: sync+restart
        - path: ./next.config.js
          target: /app/next.config.js
          action: sync+restart
    env_file:
      - ./.env
